name: "Label PRs"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  labelling:
    name: "Apply Labels"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v3

    - name: "Run Labeler"
      uses: actions/labeler@v4
